repos:
  - repo: local
    hooks:
      - id: erep-guard
        name: EREP guard
        entry: python tools/erep_guard.py --repo . --max-path-length 180
        language: system
        pass_filenames: false
