# Enforced rules/policies with versioning (what the system actually enforces)
version: 1
table: configs
columns:
  - { name: id,            type: string, required: true }       # CFG-area-slug-vN
  - { name: area,          type: enum,   required: true, values: [ci, repo, signing, security, packaging, erep, data, ai, market, risk] }
  - { name: version,       type: int,    required: true }
  - { name: status,        type: enum,   required: true, values: [active, archived] }
  - { name: rationale_md,  type: string, required: true }
  - { name: enforcement_md,type: string, required: true }
  - { name: evidence,      type: list[string], required: false }
  - { name: supersedes,    type: list[string], required: false }
  - { name: superseded_by, type: list[string], required: false }
  - { name: source_file,   type: string, required: true }
  - { name: source_sha256, type: string, required: true }
constraints:
  primary_key: [id]
