# ERQ-META-BEGIN
# {"doc_type":"config","spec_version":"2.2","source_baseline_hash":"d0ae1e584b81c6470bec874c69019e0b4d20fa93d3b14c7ec013d1c2246863fa","provenance":{"build_id":"7fc1d1f7-a863-4742-9017-04b03c3e0fd0","built_at":"2025-09-12T02:41:58Z","builder":"EREP v2.2","tools":{"python":"3.11.8"}},"governance_links":{"acceptance_gates":"00_repo/.cbr/acceptance_gates.yaml","registry":"00_repo/.cbr/registry.json","audit_log":"00_repo/.cbr/audit_log.json"},"canonicalization":{"encoding":"utf-8","newline":"LF","sort_keys":true},"integrity":{"algo":"sha256","canonical_scope":"payload","value":"51f6121b34853ba6ed851e1df57358b80692dde26c09fbe62a1e4c954bd13952"}}
# ERQ-META-END
version: 1
indicators:
  - name: rsi
    formula: "Wilder RSI"
    params: { period: 14 }
    lookback_bars: 200
    sampling: close
    outputs: [ rsi ]
    validation: { range: [0,100] }
  - name: ema_fast
    formula: "EMA"
    params: { period: 12 }
    outputs: [ ema12 ]
  - name: ema_slow
    formula: "EMA"
    params: { period: 26 }
    outputs: [ ema26 ]
  - name: solar_kp
    formula: "Normalized Kp index"
    params: { window: 24h }
    sampling: external_feed
    outputs: [ kp_norm ]
    missing_policy: forward_fill_6h
backtest_defaults:
  warmup_bars: 300
  missing_policy: drop_row_if_missing_critical
