# ERQ-META-BEGIN
# {"canonicalization": {"encoding": "utf-8", "newline": "LF", "sort_keys": true}, "doc_type": "yaml_document", "governance_links": {"acceptance_gates": "00_repo/.cbr/acceptance_gates.yaml", "audit_log": "00_repo/.cbr/audit_log.json", "registry": "00_repo/.cbr/registry.json"}, "integrity": {"algo": "sha256", "canonical_scope": "payload", "value": "64058236e55e2c02d6b0ab108d0d50e3a30aca032b645148d45d2f4f9d94002a"}, "provenance": {"build_id": "874ffd36-5286-4b49-9d90-183b77e1219b", "builder": "EREP v2.4 (FULL)", "built_at": "2025-09-12T18:31:46Z", "tools": {"hash": "sha256", "python": "3.11.8"}}, "source_baseline_hash": "7f565790af98f9fe5be6c6ad46ed2ab080bdbb080293d93dbf3b522d8bdc6149", "spec_version": "2.4"}
# ERQ-META-END
# ERQ-META-BEGIN
# {"doc_type":"machine","spec_version":"2.0","source_baseline_hash":"246d0097ad23b1bdf7615f56f441385b54ce69534d64aa58cff0ba194d67c854","provenance":{"erep_version":"2.2","build_id":"b5ea0a07-8e22-4f6a-9db4-9bbd9e9c5fe2","built_at":"2025-09-12T01:58:15Z","tools":{"python":"3.11.8","hashlib":"sha256"}},"governance_links":{"acceptance_gates":"00_repo/.cbr/acceptance_gates.yaml","registry":"00_repo/.cbr/registry.json","audit_log":"00_repo/.cbr/audit_log.json"},"canonicalization":{"encoding":"utf-8","newline":"LF","sort_keys":true},"integrity":{"algo":"sha256","canonical_scope":"payload","value":"611958d370575df8cb39d3bc70d6d4aee3500f1b0d3133b6b2b7f047d1b77a19"}}
# ERQ-META-END
# ERQ-META-BEGIN
# {"canonicalization": {"encoding": "utf-8", "newline": "LF", "sort_keys": true}, "doc_type": "workflow", "governance_links": {"acceptance_gates": "00_repo/.cbr/acceptance_gates.yaml", "audit_log": "00_repo/.cbr/audit_log.json", "registry": "00_repo/.cbr/registry.json"}, "integrity": {"algo": "sha256", "canonical_scope": "payload", "value": "604cea711dde3863ca4cf26ceebf3090c31dc45439356b4fbdfb324e64b741d8"}, "provenance": {"build_id": "f7f3dd91-1786-45d1-bac4-0f565d48d93f", "builder": "ENERQIS RC1c builder", "built_at": "2025-09-10T00:46:55Z", "tools": {"hashlib": "sha256", "python": "3.10"}}, "source_baseline_hash": "471210aae34a0cb71fa200aa901d8747e7d0e4f1b6e68781f000f4e17cc22cbb", "spec_version": "1.0"}
# ERQ-META-END
name: Synthesis
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * 1-5"
env:
  TZ: UTC
  PYTHONDONTWRITEBYTECODE: "1"
jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: "3.10", cache: "pip" }
      - run: |
          python -m pip install --upgrade pip
          pip install -r ci/requirements.txt
      - name: Validate workflow spec
        run: |
          python ci/validate_workflow.py             --spec 01_MasterControl/machine/workflow_synthesis.yaml             --schema 01_MasterControl/machine/workflows/schema/workflow.schema.json
      - name: Run synthesis (deterministic)
        run: |
          python tools/synthesize.py             --spec 01_MasterControl/machine/workflow_synthesis.yaml             --seed 1729 --tz UTC --strict
      - name: Enforce acceptance gates
        run: |
          python ci/enforce_gates.py             --allowed-roots 03_Data/machine 06_System/machine 11_Research/machine 13_OpsLog/machine 01_MasterControl/machine/validation_logs             --forbid-placeholders --schemas
      - name: Compute manifests + pending hashes
        run: |
          python ci/compute_manifests.py --modules 03 06 11 13 01 --out 01_MasterControl/machine/validation_logs/manifest_after.json
          python ci/emit_pending_hashes.py --manifest 01_MasterControl/machine/validation_logs/manifest_after.json --out 00_repo/.cbr/rc/pending_hashes.json
      - name: Package synthesis outputs
        run: |
          python ci/package_rc.py             --include 03_Data/machine 06_System/machine 11_Research/machine 01_MasterControl/machine/validation_logs             --out packages/rc/pending/ENERQIS_Synthesis_Output.zip
      - uses: actions/upload-artifact@v4
        with:
          name: enerqis-synthesis-${{ github.run_id }}
          path: |
            packages/rc/pending/ENERQIS_Synthesis_Output.zip
            packages/rc/pending/ENERQIS_Synthesis_Output.zip.sha256
            00_repo/.cbr/rc/pending_hashes.json
            01_MasterControl/machine/validation_logs/manifest_after.json
