# ERQ-META-BEGIN
# {"canonicalization": {"encoding": "utf-8", "newline": "LF", "sort_keys": true}, "doc_type": "yaml_document", "governance_links": {"acceptance_gates": "00_repo/.cbr/acceptance_gates.yaml", "audit_log": "00_repo/.cbr/audit_log.json", "registry": "00_repo/.cbr/registry.json"}, "integrity": {"algo": "sha256", "canonical_scope": "payload", "value": "e6335d56ad13642192a2775b421f7843809a196ea2249e2b2b91affa8a9ea78b"}, "provenance": {"build_id": "b22322b9-595c-4bb9-9ed8-ec5a096c4111", "builder": "EREP v2.4 (FULL)", "built_at": "2025-09-12T18:31:46Z", "tools": {"hash": "sha256", "python": "3.11.8"}}, "source_baseline_hash": "7f565790af98f9fe5be6c6ad46ed2ab080bdbb080293d93dbf3b522d8bdc6149", "spec_version": "2.4"}
# ERQ-META-END
# ERQ-META-BEGIN
# {"doc_type":"machine","spec_version":"2.0","source_baseline_hash":"246d0097ad23b1bdf7615f56f441385b54ce69534d64aa58cff0ba194d67c854","provenance":{"erep_version":"2.2","build_id":"b5ea0a07-8e22-4f6a-9db4-9bbd9e9c5fe2","built_at":"2025-09-12T01:58:15Z","tools":{"python":"3.11.8","hashlib":"sha256"}},"governance_links":{"acceptance_gates":"00_repo/.cbr/acceptance_gates.yaml","registry":"00_repo/.cbr/registry.json","audit_log":"00_repo/.cbr/audit_log.json"},"canonicalization":{"encoding":"utf-8","newline":"LF","sort_keys":true},"integrity":{"algo":"sha256","canonical_scope":"payload","value":"ba6e82a43459ae1392658f84724c843a8154cda146f9ed22f7c42fb165880167"}}
# ERQ-META-END
# ERQ-META-BEGIN
# {"canonicalization": {"encoding": "utf-8", "newline": "LF", "sort_keys": true}, "doc_type": "workflow", "governance_links": {"acceptance_gates": "00_repo/.cbr/acceptance_gates.yaml", "audit_log": "00_repo/.cbr/audit_log.json", "registry": "00_repo/.cbr/registry.json"}, "integrity": {"algo": "sha256", "canonical_scope": "payload", "value": "106c323c47685306de10ee4e118f062986ffaffd1fb432296ccaa9b673edc44c"}, "provenance": {"build_id": "f7f3dd91-1786-45d1-bac4-0f565d48d93f", "builder": "ENERQIS RC1c builder", "built_at": "2025-09-10T00:46:55Z", "tools": {"hashlib": "sha256", "python": "3.10"}}, "source_baseline_hash": "471210aae34a0cb71fa200aa901d8747e7d0e4f1b6e68781f000f4e17cc22cbb", "spec_version": "1.0"}
# ERQ-META-END
name: Package
on: [workflow_dispatch]
env: { TZ: UTC }
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build package
        run: |
          python tools/scripts/package_latest.py --out dist/enerqis_latest.zip
          python tools/scripts/validate_package.py --path dist/enerqis_latest.zip
      - uses: actions/upload-artifact@v4
        with:
          name: enerqis-package-${{ github.run_id }}
          path: dist/enerqis_latest.zip
