Param(
  [string]$BaselineTag = ""
)

$ErrorActionPreference = 'Stop'

$ts = Get-Date -Format "yyyy-MM-dd HH:mm:ssK"

New-Item -ItemType Directory -Force -Path "13_OpsLog/views" | Out-Null
New-Item -ItemType Directory -Force -Path "05_Blueprint/MASTER" | Out-Null

$hdr = @"
> Generated by tools/opslog-render.ps1 (scaffold preview)
> Timestamp: $ts
> Baseline:  $BaselineTag
"@

function Write-View($path, $title, $body) {
  $content = "# $title`n`n$hdr`n`n$body`n"
  $content | Set-Content -Encoding utf8 -NoNewline $path
  Write-Host "Wrote $path"
}

Write-View "13_OpsLog/views/scorecard.md" "Scorecard (Preview)" @"
**Headline Scores**
- Delivery: 7.5/10 — Levers to 9.5: CI reliability SLO, flaky test budget, release burndown visible.
- Security: 8.5/10 — Levers to 9.5: secrets scan gate + monthly red-team drills.
- Quality: 7.0/10 — Levers to 9.5: coverage floor, bug bar, owner-on-call.

**Why moved**: Adoption of SOPS/age baseline (+), added pre-commit guards (+), no prod incidents (±).
"@

Write-View "13_OpsLog/views/blueprint_delta.md" "Blueprint Delta (Preview)" @"
Top plan changes vs last baseline:
- Encrypted dotenvs in Git via SOPS (demo/api/prod).
- Helpers added for quick rotate/encrypt/decrypt.
- Line ending policy added to avoid CRLF churn.
"@

Write-View "13_OpsLog/views/mission_control.md" "Mission Control (Preview)" @"
- Required checks: passing (pinned actions, plaintext guard, preview render).
- Next window: enable optional sops-smoketest workflow.
"@

Write-View "13_OpsLog/views/opslog_digest.md" "Opslog Digest (Preview)" @"
Highlights:
- Pre-commit guard and LF policy merged.
- Prod dotenv added through PR with SOPS encryption.
- Helpers shipped; local smoke tests pass.
"@

Write-View "13_OpsLog/views/repo_delta.md" "Repo Delta (Preview)" @"
Key merges:
- #59 pre-commit + plaintext env guard
- #60 LF/CRLF policy
- #61 SOPS helpers
- #62 prod dotenv
"@

Write-View "13_OpsLog/views/risk_register.md" "Risk Register (Preview)" @"
1) Secret handling regressions — Mitigation: keep SOPS preflight mandatory.
2) Action pin drift — Mitigation: pin guard stays and is monitored.
"@

# Mirror mission control to blueprint master
Get-Content "13_OpsLog/views/mission_control.md" | Set-Content -Encoding utf8 -NoNewline "05_Blueprint/MASTER/mission_control.md"
