name: dependabot auto-merge

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    # Only act on PRs opened by Dependabot
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Auto-enable auto-merge for safe GitHub Actions bumps (minor/patch)
      - name: Enable auto-merge (squash)
        if: >
          steps.meta.outputs.package-ecosystem == 'github-actions' &&
          (steps.meta.outputs.update-type == 'version-update:semver-minor' ||
           steps.meta.outputs.update-type == 'version-update:semver-patch')
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
