name: EREP Equivalence Guard

on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  erep-equivalence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
      - name: Equivalence check (FULL -> COMPLIANCE_ONLY)
        run: |
          python tools/scripts/erep_equivalence_check.py             --policy 00_repo/.cbr/erep_policy.json             --root .
