name: EREP Guard

on:
  pull_request:
      branches: [ main ]
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  erep-guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run erep guard
        run: |
          python tools/erep_guard.py --repo . --max-path-length 180
