name: EREP Guard

on:
  pull_request:
      branches: [ main ]
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  erep-guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run erep guard
        run: |
          python tools/erep_guard.py --repo . --max-path-length 180
