# ERQ-META-BEGIN
# {"doc_type": "workflow", "spec_version": "2.0", "source_baseline_hash": "471210aae34a0cb71fa200aa901d8747e7d0e4f1b6e68781f000f4e17cc22cbb", "provenance": {"build_id": "7f0ca3e6-b6aa-4ace-b2e1-d845ffd4ae8f", "built_at": "2025-09-11T21:56:19Z", "builder": "EREP v2.0", "tools": {"python": "3.11", "hashlib": "sha256"}}, "governance_links": {"acceptance_gates": "00_repo/.cbr/acceptance_gates.yaml", "registry": "00_repo/.cbr/registry.json", "audit_log": "00_repo/.cbr/audit_log.json"}, "canonicalization": {"encoding": "utf-8", "newline": "LF", "sort_keys": true}, "integrity": {"algo": "sha256", "canonical_scope": "payload", "value": "84ea1cb2179d3d481a472252ee23d0f24f67285e8713c2db1a0bbfeee1e16b0e"}}
# ERQ-META-END
name: EREP v1.1

on:
  pull_request:
  push:
    branches: [ main, bootstrap-checks ]

permissions:
  contents: read

env:
  TZ: UTC

jobs:
  erep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.10'
          cache: pip

      # (This first install block existed before; keeping it intact)
      - run: |
          python -m pip install --upgrade pip
          pip install -r ci/requirements.txt || true

      - name: Install deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          pip install -r ci/requirements.txt || true

      - name: Prepare report directory
        run: mkdir -p out/erep_v1_1

      - name: Run EREP v1.1
        run: |
          set -e
          if [ -f tools/erep_scan.py ]; then
            python tools/erep_scan.py \
              --repo . \
              --structure 00_repo/.cbr/structure_lock.json \
              --gates 00_repo/.cbr/acceptance_gates.yaml \
              --out out/erep_v1_1 \
              --baseline-hash 471210aae34a0cb71fa200aa901d8747e7d0e4f1b6e68781f000f4e17cc22cbb
          elif [ -f tools/scripts/validate_structure.py ]; then
            python tools/scripts/validate_structure.py \
              --repo . \
              --structure 00_repo/.cbr/structure_lock.json \
              --gates 00_repo/.cbr/acceptance_gates.yaml \
              --out out/erep_v1_1 \
              --baseline-hash 471210aae34a0cb71fa200aa901d8747e7d0e4f1b6e68781f000f4e17cc22cbb
          else
            echo "::error::Could not find EREP runner script (tools/erep_scan.py or tools/scripts/validate_structure.py)"
            echo "Repo tree for debugging:"
            ls -R
            exit 2
          fi

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: erep-v1_1-${{ github.run_id }}
          path: out/erep_v1_1/**
          if-no-files-found: ignore
