name: opslog-sync

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  validate_and_render:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for tags/ranges

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "13_OpsLog/scripts/requirements.txt") {
            pip install -r 13_OpsLog/scripts/requirements.txt
          }

      - name: Validate SSOT schemas
        run: |
          python 13_OpsLog/scripts/30_validate_schemas.py `
            --schemas 13_OpsLog/SCHEMA `
            --ssot 13_OpsLog/SSOT

      - name: Render views (history/decisions/systems/next/scorecard/mission)
        run: |
          python 13_OpsLog/scripts/40_render.py `
            --config 13_OpsLog/oplogs_render.yml

      - name: Generate Commit Ledger
        shell: pwsh
        run: |
          $since = (git describe --tags --abbrev=0 --match 'scorecard-*' 2>$null)
          if (-not $since) { $since = "4 weeks ago" }
          ./13_OpsLog/scripts/commit_ledger.ps1 -Since "$since" -Output "13_OpsLog/LEDGER/commit_ledger.md"

      - name: Upload CI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opslog-ci
          path: |
            13_OpsLog/DERIVED/ci/ci_validation.json
            13_OpsLog/DERIVED/ci/ci_rendered.md
            13_OpsLog/DERIVED/ci/ci_mission_control.md
            13_OpsLog/LEDGER/commit_ledger.md
