name: opslog-preview
on:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jsonschema
      - name: Run semantic overlay (deterministic heuristic mode)
        run: |
          python 13_OpsLog/overlays/semantic_preview/semantic_overlay.py --config 13_OpsLog/overlays/semantic_preview/config/semantic_overlay.yaml --out 13_OpsLog/overlays/semantic_preview/DERIVED/evidence_tickets.jsonl
      - name: Upload evidence tickets
        uses: actions/upload-artifact@v4
        with:
          name: opslog-preview
          path: 13_OpsLog/overlays/semantic_preview/DERIVED/evidence_tickets.jsonl
