name: pre-commit

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

# Avoid wasting minutes: cancel older runs for the same PR/branch
concurrency:
  group: pre-commit-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: pip

      - name: Cache pre-commit env
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: ${{ runner.os }}-precommit-

      - name: Run pre-commit (changed files only)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: >-
            --from-ref ${{ github.event.pull_request.base.sha }}
            --to-ref   ${{ github.sha }}
